import { router, publicProcedure } from "../trpc";
import { supabaseAdmin } from "@/lib/supabase/server";

export const playersRouter = router({
  // Explicit column list + sports join. Two consumer-side reasons:
  //   1. Avoids select("*") leaking any future columns we wouldn't want public.
  //   2. Surfaces the sport NAME (via the join) so client filters can compare
  //      against match.league without an extra round-trip. The schema only
  //      stores sport_id (UUID) — older code that referenced p.sport (text)
  //      had been silently failing since the FK migration; B9 fixes that.
  getAll: publicProcedure.query(async () => {
    // college_id is intentionally omitted — types/supabase.ts hasn't been
    // regenerated since the column was added. CollegeProfilePage doesn't read
    // through this router (it queries supabase directly), so no consumer is
    // affected. Add it back here once types are regenerated by the teammate.
    const { data, error } = await supabaseAdmin
      .from("players")
      .select(`
        id,
        team_id,
        name,
        jersey_number,
        position,
        photo_url,
        is_active,
        created_at,
        sport:sport_id (id, name)
      `);
    if (error) throw error;
    return data || [];
  }),
});
