import Box from "@/components/matches/Box";
import { Match } from "@/types";

export default function MatchesPage() {
  // Replace this with your actual database call
  const matches: Match[] = [
	{
      id: 1,
      league: "PREMIER LEAGUE",
      leagueLogo: "PL",
      country: "England",
      status: "FT",
      statusType: "finished",
      date: "2026-03-12",
      time: "15:00",
      homeTeam: "Manchester City",
      homeTeamShort: "MCI",
      awayTeam: "Arsenal",
      awayTeamShort: "ARS",
      homeScore: 3,
      awayScore: 1,
      minute: null,
      homeScorers: ["Haaland 12'", "De Bruyne 45'"],
      awayScorers: ["Saka 34'"],
    },
    {
      id: 2,
      league: "CHAMPIONS LEAGUE",
      leagueLogo: "CL",
      country: "Europe",
      status: "LIVE",
      statusType: "live",
      date: "2026-03-12",
      time: "21:00",
      homeTeam: "Atletico Madrid",
      homeTeamShort: "ATM",
      awayTeam: "Juventus",
      awayTeamShort: "JUV",
      homeScore: 1,
      awayScore: 0,
      minute: "43'",
      homeScorers: ["Griezmann 38'"],
      awayScorers: [],
    },
    {
      id: 3,
      league: "LA LIGA",
      leagueLogo: "LL",
      country: "Spain",
      status: "UPCOMING",
      statusType: "upcoming",
      date: "2026-03-13",
      time: "20:00",
      homeTeam: "Real Madrid",
      homeTeamShort: "RMA",
      awayTeam: "Barcelona",
      awayTeamShort: "BAR",
      homeScore: null,
      awayScore: null,
      minute: null,
      homeScorers: [],
      awayScorers: [],
    },
    {
      id: 4,
      league: "BUNDESLIGA",
      leagueLogo: "BL",
      country: "Germany",
      status: "FT",
      statusType: "finished",
      date: "2026-03-12",
      time: "18:30",
      homeTeam: "Bayern Munich",
      homeTeamShort: "BAY",
      awayTeam: "Dortmund",
      awayTeamShort: "BVB",
      homeScore: 4,
      awayScore: 0,
      minute: null,
      homeScorers: ["Kane 8'", "Kane 34'"],
      awayScorers: [],
    },
    {
      id: 5,
      league: "SERIE A",
      leagueLogo: "SA",
      country: "Italy",
      status: "UPCOMING",
      statusType: "upcoming",
      date: "2026-03-13",
      time: "20:45",
      homeTeam: "Inter Milan",
      homeTeamShort: "INT",
      awayTeam: "AC Milan",
      awayTeamShort: "MIL",
      homeScore: null,
      awayScore: null,
      minute: null,
      homeScorers: [],
      awayScorers: [],
    },
    {
      id: 6,
      league: "LIGUE 1",
      leagueLogo: "L1",
      country: "France",
      status: "FT",
      statusType: "finished",
      date: "2026-03-12",
      time: "21:00",
      homeTeam: "PSG",
      homeTeamShort: "PSG",
      awayTeam: "Marseille",
      awayTeamShort: "MAR",
      homeScore: 3,
      awayScore: 0,
      minute: null,
      homeScorers: ["Mbappé 5'"],
      awayScorers: [],
    },

    ];

  return <Box matches={matches} />;
}
